/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

//#include "colors.h"
#include "widgetstyles.h"
#include "gui.h"
#include "../src/ginput/ginput_driver_mouse.h"
#include "gpio.h"

// GListeners
GListener glistener;

// GHandles
GHandle ghContainerPage0;
GHandle ghConsole1;
GHandle ghButton1;
//GHandle ghLabel1;

// Fonts
font_t dejavu_sans_10, font_1, font_2;

static void createPagePage0(void)
{
	GWidgetInit wi;
	gwinWidgetClearInit(&wi);

	// create container widget: ghContainerPage0
	wi.g.show = FALSE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 240;
	wi.g.height = 320;
	wi.g.parent = 0;
	wi.text = "Container";
	wi.customDraw = 0;
	wi.customParam = 0;
	wi.customStyle = 0;
	ghContainerPage0 = gwinContainerCreate(0, &wi, 0);

	// Create console widget: ghConsole1
	wi.g.show = TRUE;
	wi.g.x = 0;
	wi.g.y = 0;
	wi.g.width = 240;
	wi.g.height = 320;
	wi.g.parent = ghContainerPage0;
	ghConsole1 = gwinConsoleCreate(0, &wi.g);
#if 0
	gwinSetColor(ghConsole1, Black);
	gwinSetBgColor(ghConsole1, White);
#else
  gwinSetColor(ghConsole1, Green);
  gwinSetBgColor(ghConsole1, Black);
#endif

//	// create button widget: ghButton1
//	wi.g.show = TRUE;
//	wi.g.x = 60;
//	wi.g.y = 270;
//	wi.g.width = 120;
//	wi.g.height = 25;
//	wi.g.parent = ghContainerPage0;
//	wi.text = "TOUCH";
//	wi.customDraw = gwinButtonDraw_Rounded;
//	wi.customParam = 0;
//	wi.customStyle = &white;
//	ghButton1 = gwinButtonCreate(0, &wi);
//	gwinSetFont(ghButton1, font_2);
//	gwinRedraw(ghButton1);

//	// Create label widget: ghLabel1
//	wi.g.show = TRUE;
//	wi.g.x = 60;
//	wi.g.y = 230;
//	wi.g.width = 120;
//	wi.g.height = 20;
//	wi.g.parent = ghContainerPage0;
//	wi.text =  "Метка";
//	wi.customDraw = gwinLabelDrawJustifiedCenter;
//	wi.customParam = 0;
//	wi.customStyle = &white;
//	ghLabel1 = gwinLabelCreate(0, &wi);
//	gwinLabelSetBorder(ghLabel1, TRUE);
}

void guiShowPage(unsigned pageIndex)
{
	// Hide all pages
	gwinHide(ghContainerPage0);

	// Show page selected page
	switch (pageIndex) {
	case 0:
		gwinShow(ghContainerPage0);
		break;

	default:
		break;
	}
}

void guiCreate(void)
{
	GWidgetInit wi;

	// Prepare fonts
	dejavu_sans_10 = gdispOpenFont("DejaVuSans10");
	font_1 = gdispOpenFont("UI2");
	font_2 = gdispOpenFont("PragmaticaKMM Regular 12");
	// Prepare images

	// GWIN settings
	gwinWidgetClearInit(&wi);
	gwinSetDefaultFont(font_1);
//	gwinSetDefaultFont(dejavu_sans_10);

	gwinSetDefaultStyle(&white, FALSE);
	gwinSetDefaultColor(Black);
	gwinSetDefaultBgColor(White);

	// Create all the display pages
	createPagePage0();

	// Select the default display page
	guiShowPage(0);

	// Console sample text
//	gwinPrintf(ghConsole1, "Ы ы Э э Ё ё Ъ ъ\nІ і Ї ї Ґ ґ Є є\n", sizeof(GMouseCalibration), 255);
}

void guiEventLoop(void)
{
	GEvent* pe;
	uint8_t i = 0;
	while (1) {
	  gfxSleepMilliseconds(100);
//	  LED_TOGGLE();
		// Get an event
		pe = geventEventWait(&glistener, 0);
		switch (pe->type) {
		  case GEVENT_GWIN_BUTTON:
		          if (((GEventGWinButton*)pe)->gwin == ghButton1) {
		            // Our button has been pressed
               i++;
		           gwinPrintf(ghConsole1, "Кнопка нажата %d\n", i);

		          }
		          break;
		}

	}
}

